use lib_common::robot::{
    CommandSchema, Example, ParameterSchema, ROBOT_HELP_SCHEMA_VERSION, RobotFlagSchema,
    RobotHelpOutput,
};
use once_cell::sync::Lazy;
use serde::Serialize;
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize)]
pub struct RobotStatusOutput {
    pub schema_version: String,
    pub tool: String,
    pub version: String,
    pub timestamp: String,
    pub status: String,
    pub checks: HashMap<String, CheckResult>,
    pub exit_code: u8,
}

#[derive(Debug, Clone, Serialize)]
pub struct CheckResult {
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub port: Option<u16>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct RobotExamplesOutput {
    pub schema_version: String,
    pub target: String,
    pub target_type: String, // "flag" | "subcommand"
    pub examples: Vec<Example>,
}

pub static EXAMPLE_REGISTRY: Lazy<RobotHelpOutput> = Lazy::new(|| RobotHelpOutput {
    schema_version: ROBOT_HELP_SCHEMA_VERSION.to_string(),
    tool: "mcp-agent-mail".to_string(),
    version: env!("CARGO_PKG_VERSION").to_string(),
    description: "Unified Server/CLI for Agent Mail".to_string(),
    robot_flags: vec![
        RobotFlagSchema {
            name: "robot-help".to_string(),
            description: "Output help in machine-readable JSON format".to_string(),
            output_format: "json".to_string(),
            examples: vec![
                Example {
                    invocation: "mcp-agent-mail --robot-help".to_string(),
                    description: "Get full CLI documentation in JSON".to_string(),
                },
                Example {
                    invocation: "mcp-agent-mail --robot-help --format yaml".to_string(),
                    description: "Get documentation in YAML format".to_string(),
                },
            ],
        },
        RobotFlagSchema {
            name: "robot-examples".to_string(),
            description: "Show usage examples for flags/subcommands".to_string(),
            output_format: "json".to_string(),
            examples: vec![
                Example {
                    invocation: "mcp-agent-mail --robot-examples --port".to_string(),
                    description: "Examples for --port flag".to_string(),
                },
                Example {
                    invocation: "mcp-agent-mail --robot-examples serve http".to_string(),
                    description: "Examples for serve http subcommand".to_string(),
                },
                Example {
                    invocation: "mcp-agent-mail --robot-examples --robot-examples".to_string(),
                    description: "Self-documenting examples".to_string(),
                },
            ],
        },
        RobotFlagSchema {
            name: "robot-status".to_string(),
            description: "Output system health status in machine-readable format".to_string(),
            output_format: "json".to_string(),
            examples: vec![
                Example {
                    invocation: "mcp-agent-mail --robot-status".to_string(),
                    description: "Check system health (JSON)".to_string(),
                },
                Example {
                    invocation: "mcp-agent-mail --robot-status --format yaml".to_string(),
                    description: "Check system health (YAML)".to_string(),
                },
            ],
        },
    ],
    commands: vec![
        CommandSchema {
            name: "serve".to_string(),
            description: "Start a server (HTTP or MCP)".to_string(),
            examples: vec![
                Example {
                    invocation: "mcp-agent-mail serve http".to_string(),
                    description: "Start HTTP server with default settings".to_string(),
                },
                Example {
                    invocation: "mcp-agent-mail serve mcp".to_string(),
                    description: "Start MCP server on stdio".to_string(),
                },
            ],
            parameters: vec![
                ParameterSchema {
                    name: "port".to_string(),
                    long: Some("--port".to_string()),
                    short: Some('p'),
                    description: "Port to bind to".to_string(),
                    param_type: Some("integer".to_string()),
                    default: None,
                    required: false,
                    possible_values: vec![],
                    env_var: Some("MCP_AGENT_MAIL_PORT".to_string()),
                },
                ParameterSchema {
                    name: "transport".to_string(),
                    long: Some("--transport".to_string()),
                    short: Some('t'),
                    description: "Transport type (sse or stdio)".to_string(),
                    param_type: Some("string".to_string()),
                    default: Some("sse".to_string()),
                    required: false,
                    possible_values: vec!["sse".to_string(), "stdio".to_string()],
                    env_var: None,
                },
            ],
            exit_codes: Default::default(),
            subcommands: vec![
                CommandSchema {
                    name: "http".to_string(),
                    description: "Start Standard HTTP Server (SSE)".to_string(),
                    examples: vec![
                        Example {
                            invocation: "mcp-agent-mail serve http --port 9000".to_string(),
                            description: "Start HTTP server on port 9000".to_string(),
                        },
                        Example {
                            invocation: "mcp-agent-mail serve http --no-ui".to_string(),
                            description: "Start headless HTTP server".to_string(),
                        },
                    ],
                    parameters: vec![ParameterSchema {
                        name: "no_ui".to_string(),
                        long: Some("--no-ui".to_string()),
                        short: None,
                        description: "Disable Web UI".to_string(),
                        param_type: Some("boolean".to_string()),
                        default: Some("false".to_string()),
                        required: false,
                        possible_values: vec![],
                        env_var: None,
                    }],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "mcp".to_string(),
                    description: "Start MCP Server (Stdio)".to_string(),
                    examples: vec![Example {
                        invocation: "mcp-agent-mail serve mcp".to_string(),
                        description: "Start standard MCP server".to_string(),
                    }],
                    parameters: vec![],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
            ],
        },
        CommandSchema {
            name: "health".to_string(),
            description: "Check server health".to_string(),
            examples: vec![],
            parameters: vec![ParameterSchema {
                name: "url".to_string(),
                long: Some("--url".to_string()),
                short: None,
                description: "Server URL to check".to_string(),
                param_type: Some("string".to_string()),
                default: Some("http://localhost:8080".to_string()),
                required: false,
                possible_values: vec![],
                env_var: Some("MCP_AGENT_MAIL_URL".to_string()),
            }],
            exit_codes: Default::default(),
            subcommands: vec![],
        },
        CommandSchema {
            name: "config".to_string(),
            description: "Manage configuration".to_string(),
            examples: vec![],
            parameters: vec![],
            exit_codes: Default::default(),
            subcommands: vec![
                CommandSchema {
                    name: "set-port".to_string(),
                    description: "Set the default binding port".to_string(),
                    examples: vec![],
                    parameters: vec![ParameterSchema {
                        name: "port".to_string(),
                        long: None,
                        short: None,
                        description: "Port number".to_string(),
                        param_type: Some("integer".to_string()),
                        default: None,
                        required: true,
                        possible_values: vec![],
                        env_var: None,
                    }],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "show-port".to_string(),
                    description: "Show the current binding port".to_string(),
                    examples: vec![],
                    parameters: vec![],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
            ],
        },
        CommandSchema {
            name: "schema".to_string(),
            description: "Export JSON schemas for all tools".to_string(),
            examples: vec![],
            parameters: vec![
                ParameterSchema {
                    name: "format".to_string(),
                    long: Some("--format".to_string()),
                    short: Some('f'),
                    description: "Output format".to_string(),
                    param_type: Some("string".to_string()),
                    default: Some("json".to_string()),
                    required: false,
                    possible_values: vec!["json".to_string(), "markdown".to_string()],
                    env_var: None,
                },
                ParameterSchema {
                    name: "output".to_string(),
                    long: Some("--output".to_string()),
                    short: Some('o'),
                    description: "Output file (stdout if not specified)".to_string(),
                    param_type: Some("string".to_string()),
                    default: None,
                    required: false,
                    possible_values: vec![],
                    env_var: None,
                },
            ],
            exit_codes: Default::default(),
            subcommands: vec![],
        },
        CommandSchema {
            name: "tools".to_string(),
            description: "List all available tools".to_string(),
            examples: vec![],
            parameters: vec![],
            exit_codes: Default::default(),
            subcommands: vec![],
        },
        CommandSchema {
            name: "install".to_string(),
            description: "Install shell alias and configuration".to_string(),
            examples: vec![],
            parameters: vec![],
            exit_codes: Default::default(),
            subcommands: vec![CommandSchema {
                name: "alias".to_string(),
                description: "Add 'am' shell alias".to_string(),
                examples: vec![],
                parameters: vec![ParameterSchema {
                    name: "force".to_string(),
                    long: Some("--force".to_string()),
                    short: None,
                    description: "Force overwrite existing alias".to_string(),
                    param_type: Some("boolean".to_string()),
                    default: Some("false".to_string()),
                    required: false,
                    possible_values: vec![],
                    env_var: None,
                }],
                exit_codes: Default::default(),
                subcommands: vec![],
            }],
        },
        CommandSchema {
            name: "service".to_string(),
            description: "Manage the background service".to_string(),
            examples: vec![],
            parameters: vec![],
            exit_codes: Default::default(),
            subcommands: vec![
                CommandSchema {
                    name: "stop".to_string(),
                    description: "Stop the running server".to_string(),
                    examples: vec![],
                    parameters: vec![ParameterSchema {
                        name: "port".to_string(),
                        long: Some("--port".to_string()),
                        short: Some('p'),
                        description: "Port to stop".to_string(),
                        param_type: Some("integer".to_string()),
                        default: None,
                        required: false,
                        possible_values: vec![],
                        env_var: Some("MCP_AGENT_MAIL_PORT".to_string()),
                    }],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "status".to_string(),
                    description: "Check if server is running".to_string(),
                    examples: vec![],
                    parameters: vec![ParameterSchema {
                        name: "port".to_string(),
                        long: Some("--port".to_string()),
                        short: Some('p'),
                        description: "Port to check".to_string(),
                        param_type: Some("integer".to_string()),
                        default: None,
                        required: false,
                        possible_values: vec![],
                        env_var: Some("MCP_AGENT_MAIL_PORT".to_string()),
                    }],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "restart".to_string(),
                    description: "Restart the server".to_string(),
                    examples: vec![],
                    parameters: vec![ParameterSchema {
                        name: "port".to_string(),
                        long: Some("--port".to_string()),
                        short: Some('p'),
                        description: "Port to restart".to_string(),
                        param_type: Some("integer".to_string()),
                        default: None,
                        required: false,
                        possible_values: vec![],
                        env_var: Some("MCP_AGENT_MAIL_PORT".to_string()),
                    }],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
            ],
        },
        CommandSchema {
            name: "share".to_string(),
            description: "Export sharing utilities".to_string(),
            examples: vec![],
            parameters: vec![],
            exit_codes: Default::default(),
            subcommands: vec![
                CommandSchema {
                    name: "keypair".to_string(),
                    description: "Generate Ed25519 signing keypair".to_string(),
                    examples: vec![],
                    parameters: vec![ParameterSchema {
                        name: "output".to_string(),
                        long: Some("--output".to_string()),
                        short: Some('o'),
                        description: "Output file for keys".to_string(),
                        param_type: Some("string".to_string()),
                        default: None,
                        required: false,
                        possible_values: vec![],
                        env_var: None,
                    }],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "verify".to_string(),
                    description: "Verify export manifest signature".to_string(),
                    examples: vec![],
                    parameters: vec![
                        ParameterSchema {
                            name: "manifest".to_string(),
                            long: Some("--manifest".to_string()),
                            short: Some('m'),
                            description: "Manifest file to verify".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "public_key".to_string(),
                            long: Some("--public-key".to_string()),
                            short: Some('p'),
                            description: "Public key for verification".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                    ],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
            ],
        },
        CommandSchema {
            name: "archive".to_string(),
            description: "Archive management (disaster recovery)".to_string(),
            examples: vec![],
            parameters: vec![],
            exit_codes: Default::default(),
            subcommands: vec![
                CommandSchema {
                    name: "save".to_string(),
                    description: "Create a restorable snapshot archive".to_string(),
                    examples: vec![],
                    parameters: vec![
                        ParameterSchema {
                            name: "label".to_string(),
                            long: Some("--label".to_string()),
                            short: Some('l'),
                            description: "Label for the archive".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "include_git".to_string(),
                            long: Some("--include-git".to_string()),
                            short: None,
                            description: "Include Git storage".to_string(),
                            param_type: Some("boolean".to_string()),
                            default: Some("false".to_string()),
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                    ],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "list".to_string(),
                    description: "List available restore points".to_string(),
                    examples: vec![],
                    parameters: vec![ParameterSchema {
                        name: "json".to_string(),
                        long: Some("--json".to_string()),
                        short: None,
                        description: "Output in JSON format".to_string(),
                        param_type: Some("boolean".to_string()),
                        default: Some("false".to_string()),
                        required: false,
                        possible_values: vec![],
                        env_var: None,
                    }],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "restore".to_string(),
                    description: "Restore from a backup archive".to_string(),
                    examples: vec![],
                    parameters: vec![
                        ParameterSchema {
                            name: "file".to_string(),
                            long: None,
                            short: None,
                            description: "Archive file (.zip)".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "yes".to_string(),
                            long: Some("--yes".to_string()),
                            short: None,
                            description: "Skip confirmation".to_string(),
                            param_type: Some("boolean".to_string()),
                            default: Some("false".to_string()),
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                    ],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "clear-and-reset".to_string(),
                    description: "Wipe all state with optional archive".to_string(),
                    examples: vec![],
                    parameters: vec![
                        ParameterSchema {
                            name: "archive".to_string(),
                            long: Some("--archive".to_string()),
                            short: None,
                            description: "Archive before wiping".to_string(),
                            param_type: Some("boolean".to_string()),
                            default: Some("false".to_string()),
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "label".to_string(),
                            long: Some("--label".to_string()),
                            short: None,
                            description: "Label for archive provided".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "yes".to_string(),
                            long: Some("--yes".to_string()),
                            short: None,
                            description: "Skip confirmation".to_string(),
                            param_type: Some("boolean".to_string()),
                            default: Some("false".to_string()),
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                    ],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
            ],
        },
        CommandSchema {
            name: "summarize".to_string(),
            description: "Summarize thread(s) in a project".to_string(),
            examples: vec![
                Example {
                    invocation: "mcp-agent-mail summarize -p my-project -t THREAD-123".to_string(),
                    description: "Summarize a single thread".to_string(),
                },
                Example {
                    invocation: "mcp-agent-mail summarize -p my-project -t THREAD-1,THREAD-2"
                        .to_string(),
                    description: "Summarize multiple threads".to_string(),
                },
                Example {
                    invocation: "mcp-agent-mail summarize -p my-project -t THREAD-123 --no-llm"
                        .to_string(),
                    description: "Get raw aggregation without LLM summarization".to_string(),
                },
                Example {
                    invocation:
                        "mcp-agent-mail summarize -p my-project -t THREAD-123 --per-thread-limit 50"
                            .to_string(),
                    description: "Limit to 50 messages per thread".to_string(),
                },
            ],
            parameters: vec![
                ParameterSchema {
                    name: "project".to_string(),
                    long: Some("--project".to_string()),
                    short: Some('p'),
                    description: "Project slug or path".to_string(),
                    param_type: Some("string".to_string()),
                    default: None,
                    required: true,
                    possible_values: vec![],
                    env_var: None,
                },
                ParameterSchema {
                    name: "thread_id".to_string(),
                    long: Some("--thread-id".to_string()),
                    short: Some('t'),
                    description: "Thread ID(s) to summarize (comma-separated)".to_string(),
                    param_type: Some("string".to_string()),
                    default: None,
                    required: true,
                    possible_values: vec![],
                    env_var: None,
                },
                ParameterSchema {
                    name: "per_thread_limit".to_string(),
                    long: Some("--per-thread-limit".to_string()),
                    short: None,
                    description: "Maximum messages per thread (default: 100)".to_string(),
                    param_type: Some("integer".to_string()),
                    default: Some("100".to_string()),
                    required: false,
                    possible_values: vec![],
                    env_var: None,
                },
                ParameterSchema {
                    name: "no_llm".to_string(),
                    long: Some("--no-llm".to_string()),
                    short: None,
                    description: "Skip LLM summarization, return raw aggregation".to_string(),
                    param_type: Some("boolean".to_string()),
                    default: Some("false".to_string()),
                    required: false,
                    possible_values: vec![],
                    env_var: None,
                },
                ParameterSchema {
                    name: "format".to_string(),
                    long: Some("--format".to_string()),
                    short: Some('f'),
                    description: "Output format".to_string(),
                    param_type: Some("string".to_string()),
                    default: Some("json".to_string()),
                    required: false,
                    possible_values: vec!["json".to_string(), "text".to_string()],
                    env_var: None,
                },
            ],
            exit_codes: Default::default(),
            subcommands: vec![],
        },
        CommandSchema {
            name: "version".to_string(),
            description: "Show version info".to_string(),
            examples: vec![],
            parameters: vec![],
            exit_codes: Default::default(),
            subcommands: vec![],
        },
        CommandSchema {
            name: "products".to_string(),
            description: "Product management".to_string(),
            examples: vec![
                Example {
                    invocation: "mcp-agent-mail products ensure p-123 --name 'My Product'"
                        .to_string(),
                    description: "Ensure a product exists".to_string(),
                },
                Example {
                    invocation: "mcp-agent-mail products link p-123 my-project".to_string(),
                    description: "Link a product to a project".to_string(),
                },
                Example {
                    invocation: "mcp-agent-mail products status p-123".to_string(),
                    description: "Show product status and linked projects".to_string(),
                },
            ],
            parameters: vec![],
            exit_codes: Default::default(),
            subcommands: vec![
                CommandSchema {
                    name: "ensure".to_string(),
                    description: "Ensure a product exists".to_string(),
                    examples: vec![],
                    parameters: vec![
                        ParameterSchema {
                            name: "product_uid".to_string(),
                            long: None,
                            short: None,
                            description: "Product UID".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "name".to_string(),
                            long: Some("--name".to_string()),
                            short: None,
                            description: "Product name".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                    ],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "link".to_string(),
                    description: "Link a product to a project".to_string(),
                    examples: vec![],
                    parameters: vec![
                        ParameterSchema {
                            name: "product_uid".to_string(),
                            long: None,
                            short: None,
                            description: "Product UID".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "project".to_string(),
                            long: None,
                            short: None,
                            description: "Project identifier".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                    ],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "status".to_string(),
                    description: "Show product status".to_string(),
                    examples: vec![],
                    parameters: vec![ParameterSchema {
                        name: "product_uid".to_string(),
                        long: None,
                        short: None,
                        description: "Product UID".to_string(),
                        param_type: Some("string".to_string()),
                        default: None,
                        required: true,
                        possible_values: vec![],
                        env_var: None,
                    }],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "search".to_string(),
                    description: "Search messages within a product".to_string(),
                    examples: vec![],
                    parameters: vec![
                        ParameterSchema {
                            name: "product_uid".to_string(),
                            long: None,
                            short: None,
                            description: "Product UID".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "query".to_string(),
                            long: None,
                            short: None,
                            description: "Search query".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "limit".to_string(),
                            long: Some("--limit".to_string()),
                            short: None,
                            description: "Result limit".to_string(),
                            param_type: Some("integer".to_string()),
                            default: Some("50".to_string()),
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                    ],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "inbox".to_string(),
                    description: "Get inbox for an agent within a product context".to_string(),
                    examples: vec![],
                    parameters: vec![
                        ParameterSchema {
                            name: "product_uid".to_string(),
                            long: None,
                            short: None,
                            description: "Product UID".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "agent".to_string(),
                            long: None,
                            short: None,
                            description: "Agent name".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "urgent_only".to_string(),
                            long: Some("--urgent-only".to_string()),
                            short: None,
                            description: "Only urgent messages".to_string(),
                            param_type: Some("boolean".to_string()),
                            default: Some("false".to_string()),
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "include_bodies".to_string(),
                            long: Some("--include-bodies".to_string()),
                            short: None,
                            description: "Include message bodies".to_string(),
                            param_type: Some("boolean".to_string()),
                            default: Some("false".to_string()),
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                    ],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
                CommandSchema {
                    name: "summarize-thread".to_string(),
                    description: "Summarize a thread".to_string(),
                    examples: vec![],
                    parameters: vec![
                        ParameterSchema {
                            name: "product_uid".to_string(),
                            long: None,
                            short: None,
                            description: "Product UID".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "thread_id".to_string(),
                            long: None,
                            short: None,
                            description: "Thread ID".to_string(),
                            param_type: Some("string".to_string()),
                            default: None,
                            required: true,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "per_thread_limit".to_string(),
                            long: Some("--per-thread-limit".to_string()),
                            short: None,
                            description: "Result limit".to_string(),
                            param_type: Some("integer".to_string()),
                            default: Some("100".to_string()),
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                        ParameterSchema {
                            name: "no_llm".to_string(),
                            long: Some("--no-llm".to_string()),
                            short: None,
                            description: "Skip LLM summarization".to_string(),
                            param_type: Some("boolean".to_string()),
                            default: Some("false".to_string()),
                            required: false,
                            possible_values: vec![],
                            env_var: None,
                        },
                    ],
                    exit_codes: Default::default(),
                    subcommands: vec![],
                },
            ],
        },
    ],
});
